[package]
name = "simplog"
version = "1.0.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "An extremely small and simple logger that has levels of output"
license = "MIT"

[lib]
name = "simplog"
path = "src/lib.rs"

[dependencies]
log = "0.3.8"